Incorporates cmdchallenge-site
* Moves common scripts under bin/
* Upgrades lambda functions to python3
* Upgrades terraform
* Removes READMEs from challenges
* New frontend
* Bumps all versions for challenges
* Adds shmt and shellcheck
* Improves the layout for solutions
* Adds checks for shell scripts
* Refactors CI variables for terraform runs
* Adds a deploy job for testing

diff --git a/cmdchallenge/ro_volume/cmdtests/replace_text_in_files b/cmdchallenge/ro_volume/cmdtests/replace_text_in_files
--- a/cmdchallenge/ro_volume/cmdtests/replace_text_in_files
+++ b/cmdchallenge/ro_volume/cmdtests/replace_text_in_files
@@ -1,18 +1,18 @@
 #!/bin/bash
 
 if ! [[ $(find . -name "*.txt" | wc -l) == 3 ]]; then
-    echo "Test failed, expecting 3 text files."
-    fail=1
+	echo "Test failed, expecting 3 text files."
+	fail=1
 fi
 
 if ! [[ $(find . -name "*.txt" -print0 | xargs -0 -n1 grep "challenges are difficult") == "" ]]; then
-    echo "Test failed, found the string 'challenges are difficult'."
-    fail=1
+	echo "Test failed, found the string 'challenges are difficult'."
+	fail=1
 fi
 
-if ! grep -q "challenges are difficult" README; then
-    echo "Test failed, files without .txt extension must remain unmodified."
-    fail=1
+if ! grep -q "challenges are difficult" not-a-text-file; then
+	echo "Test failed, files without .txt extension must remain unmodified."
+	fail=1
 fi
 
 [[ -n "$fail" ]] && exit 1
